# Generated by Django 3.2.9 on 2022-04-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('-name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Список заказанных товаров'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-date',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='parameters',
            options={'ordering': ('-name',), 'verbose_name': 'Имя параметра', 'verbose_name_plural': 'Имена параметров'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр продукта', 'verbose_name_plural': 'Список параметров продукта'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Список продуктов'},
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'ordering': ('-name',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.RemoveConstraint(
            model_name='productparameter',
            name='unique_product_parameter',
        ),
        migrations.RemoveField(
            model_name='productparameter',
            name='parameter',
        ),
        migrations.AddField(
            model_name='orders',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.contacts', verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='productparameter',
            name='parameter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='backend.parameters', verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='productsinfo',
            name='external_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Внешний ИД'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='backend.productsinfo', verbose_name='Информация о продукте'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('basket', 'Статус корзины'), ('new', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название параметра'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='product_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='backend.productsinfo', verbose_name='Информация о продукте'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddConstraint(
            model_name='orderitems',
            constraint=models.UniqueConstraint(fields=('order_id', 'product_info_id'), name='unique_order_item'),
        ),
        migrations.AddConstraint(
            model_name='productparameter',
            constraint=models.UniqueConstraint(fields=('product_info_id', 'parameter_id'), name='unique_product_parameter'),
        ),
        migrations.AddConstraint(
            model_name='productsinfo',
            constraint=models.UniqueConstraint(fields=('product_id', 'shop_id', 'external_id'), name='unique_product_info'),
        ),
    ]
